app/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path(
        "add-to-cart/<int:pk>/",
        views.AddToCartView.as_view(),
        name="add-to-cart",
    ),
    path(
        "subtract-from-cart/<int:pk>/",
        views.SubtractFromCartView.as_view(),
        name="subtract-from-cart",
    ),
    path(
        "remove-from-cart/<int:pk>/",
        views.RemoveFromCartView.as_view(),
        name="remove-from-cart",
    ),
]

app/customers/urls.py
from django.urls import path

from . import views

app_name = "customers"


urlpatterns = [
    path("", views.CustomerPanelView.as_view(), name="customer_panel"),
    path(
        "profile-settings/",
        views.CustomerProfileView.as_view(),
        name="profile_settings",
    ),
    path("change-password/", views.ChangePasswordView.as_view(), name="change_password"),
    path("wish-list/", views.WishListView.as_view(), name="wish_list"),
    path("orders/", views.OrdersView.as_view(), name="orders"),
    path(
        "orders/details/<int:pk>/",
        views.OrderDetailView.as_view(),
        name="details_order",
    ),
]

app/marketplace/urls.py
from django.urls import path

from . import views

app_name = "marketplace"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home_view"),
    path("add-wish/<int:id>/", views.AddToWishListView.as_view(), name="add_wish"),
    path("item-details/<slug:slug>", views.ItemFullView.as_view(), name="item_details"),
    path("shop/<slug:slug>/items/", views.ShopView.as_view(), name="shop"),
    path(
        "shop/<slug:slug>/items/<slug:category_slug>/",
        views.ShopView.as_view(),
        name="shop_by_category",
    ),
]

app/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"

urlpatterns = [
    path("add/", views.add, name="add"),
]

app/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path("", include("marketplace.urls")),
    path("shop-admin/", include("shop.urls")),
    path("customers/", include("customers.urls")),
    path("cart/", include("cart.urls")),
    path("payment/", include("payment.urls")),
    path("orders/", include("orders.urls")),
]
if settings.ADMIN_ENABLED:
    urlpatterns += [path("admin/", admin.site.urls)]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Separate folder for each user
def user_avatar(instance, filename):
    return "avatar/{0}/{1}".format(instance.user.id, filename)


class UserManager(BaseUserManager):
    # Custom User Manager
    def create_user(self, first_name, last_name, username, email, role=None, password=None):
        if not email:
            raise ValueError("User must have an email address.")
        if not username:
            raise ValueError("User must have an username.")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            role=role,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password=None):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        user.is_superuser = True
        user.is_active = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    # Shop or customer account
    SHOP = 2
    CUSTOMER = 1

    ROLE_CHOICE = (
        (SHOP, "Shop"),
        (CUSTOMER, "Customer"),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)

    # Required fields
    created_date = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    # User permissions
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "first_name", "last_name"]

    objects = UserManager()

    def __str__(self):
        return self.email


class UserProfile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, blank=True)
    profile_picture = models.ImageField(upload_to=user_avatar, blank=True, null=True)
    phone_number = PhoneNumberField(max_length=14, blank=True)

    address = models.CharField(max_length=250, blank=True, null=True)
    country = models.CharField(max_length=16, blank=True, null=True)
    city = models.CharField(max_length=16, blank=True, null=True)
    state = models.CharField(max_length=40, blank=True, null=True)
    pin_code = models.CharField(max_length=15, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)


class DailyLetter(models.Model):
    email = models.EmailField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.email.split("@")[0]

app/orders/models.py
from django.contrib.auth import get_user_model
from django.db import models
from shop.models import Item, Shop


class Order(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="order_user",
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=14, blank=True)

    address = models.CharField(max_length=250, blank=True, null=True)
    country = models.CharField(max_length=16, blank=True, null=True)
    city = models.CharField(max_length=16, blank=True, null=True)
    state = models.CharField(max_length=40, blank=True, null=True)
    pin_code = models.CharField(max_length=15, blank=True, null=True)

    billing_status = models.BooleanField(default=False)
    order_key = models.CharField(max_length=200)
    total_paid = models.DecimalField(max_digits=7, decimal_places=2)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    def __str__(self):
        return str(self.created_at)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    item = models.ForeignKey(Item, related_name="order_items", on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.item.name) + "-" + str(self.item.shop) + "-" + str(self.order.order_key)[-8:-1]


class ShopOrder(models.Model):
    STATUS_CHOICES = (
        ("New", "New"),
        ("In Process", "In Process"),
        ("Sent", "Sent"),
    )

    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)

    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default="New")

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("shop", "order")
        ordering = ("-created_at",)

    def __str__(self):
        return f"{self.shop.shop_name} - {self.order}"

    def save(self, *args, **kwargs):
        order_items = self.order.items.filter(item__shop=self.shop)
        price = sum(item.quantity * item.price for item in order_items)
        self.price = price
        super().save(*args, **kwargs)

app/customers/forms.py
from accounts.models import UserProfile
from django import forms
from django.contrib.auth import get_user_model
from django.forms.widgets import NumberInput
from phonenumber_field.widgets import PhoneNumberPrefixWidget


class UserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = [
            "first_name",
            "last_name",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {
                    "class": "form-control form-control-lg",
                }
            )


class UserProfileForm(forms.ModelForm):
    dob = forms.DateField(widget=NumberInput(attrs={"type": "date"}))

    class Meta:
        model = UserProfile
        fields = [
            "profile_picture",
            "phone_number",
            "address",
            "country",
            "state",
            "city",
            "pin_code",
            "dob",
        ]
        widgets = {  # Here
            "phone": PhoneNumberPrefixWidget(initial="PL"),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["dob"].required = False
        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {
                    "class": "form-control form-control-lg",
                }
            )

app/customers/views.py
from accounts.models import UserProfile
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import PasswordChangeView
from django.core.cache import cache
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from orders.models import Order
from shop.models import Item

from .forms import UserForm, UserProfileForm


class CheckShopMixin(UserPassesTestMixin):
    def test_func(self):
        return not self.request.user.is_staff


class CustomerPanelView(LoginRequiredMixin, generic.TemplateView):
    template_name = "customers/customer_panel.html"


class CustomerProfileView(LoginRequiredMixin, generic.UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    user_form_class = UserForm
    template_name = "customers/customer_profile.html"
    success_url = reverse_lazy("customers:customer_panel")

    def get_object(self, queryset=None):
        return self.request.user.userprofile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["user_form"] = self.user_form_class(
                self.request.POST,
                instance=self.request.user,
            )
        else:
            context["user_form"] = self.user_form_class(instance=self.request.user)
            context["form"] = self.form_class(instance=self.request.user.userprofile)
            context["profile"] = self.request.user.userprofile
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        user_form = context["user_form"]

        if user_form.is_valid():
            user_form.save()
            return super().form_valid(form)
        else:
            messages.error(self.request, user_form.errors)
            return self.render(
                self.request,
                self.template_name,
                context={"form": form, "user_form": user_form},
            )

        cache.delete("user_profile_{}".format(self.request.user.userprofile.pk))
        return super().form_valid(form)

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        messages.error(self.request, form.errors)
        return render(self.request, self.template_name, context=context)


class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    model = get_user_model()
    template_name = "accounts/change_password.html"
    success_url = reverse_lazy("customers:customer_panel")

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, "Password has been changed!")

        return super().form_valid(form)

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        messages.error(self.request, form.errors)

        return render(self.request, self.template_name, context=context)


class WishListView(LoginRequiredMixin, generic.ListView):
    model = Item
    template_name = "customers/wish_list.html"
    context_object_name = "wish_list"
    paginate_by = 4

    def get_queryset(self):
        queryset = self.request.user.wish_list.all()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["wish_count"] = self.request.user.wish_list.count()
        context["items"] = Item.objects.all()
        return context


class OrdersView(LoginRequiredMixin, generic.ListView):
    template_name = "customers/orders.html"
    paginate_by = 10
    context_object_name = "orders"

    def get_queryset(self):
        queryset = Order.objects.filter(user=self.request.user, billing_status=True)
        return queryset


class OrderDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "customers/details_order.html"
    context_object_name = "orders"

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, billing_status=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["orderitems"] = self.get_object().items.all()
        context["total"] = self.get_object().total_paid
        return context

app/orders/views.py
from accounts.tasks import new_order_notification, send_order_confirmation
from cart.models import Cart
from django.contrib import messages
from django.http.response import JsonResponse

from .models import Order, OrderItem, ShopOrder


def add(request):
    user = request.user
    cart_items = Cart.objects.filter(user=user)

    if request.POST.get("action") == "post":
        user_id = user.id
        order_key = request.POST.get("order_key")
        carttotal = sum([it.quantity * it.item.price for it in cart_items])
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        phone_number = request.POST.get("phone_number")
        email_address = request.user.email
        address = request.POST.get("address")
        state = request.POST.get("state")
        city = request.POST.get("city")
        pin_code = request.POST.get("pin_code")
        country = request.POST.get("country")

        # check if order already exists
        if not Order.objects.filter(order_key=order_key).exists():
            order = Order.objects.create(
                user_id=user_id,
                first_name=first_name,
                last_name=last_name,
                phone_number=phone_number,
                address=address,
                country=country,
                city=city,
                state=state,
                pin_code=pin_code,
                total_paid=carttotal,
                order_key=order_key,
            )
            # create order items
            order_id = order.pk
            for item in cart_items:
                shop = item.item.shop
                OrderItem.objects.create(
                    order_id=order_id,
                    item=item.item,
                    price=item.item.price,
                    quantity=item.quantity,
                )
                shop_order, created = ShopOrder.objects.get_or_create(
                    shop=shop,
                    order=order,
                )
                if not created:
                    shop_order.save()

        response = JsonResponse({"success": "Return something"})
        messages.success(request, "Order successfully placed!")
        return response


def payment_confirmation(data):
    Order.objects.filter(order_key=data).update(billing_status=True)
    order = Order.objects.get(order_key=data)
    # email to all shops in the order
    new_order_notification.delay(order.pk)
    # email to the user
    send_order_confirmation.delay(order.pk)

app/templates/customers/customer_panel.html
{% extends "includes/base.html" %}
{% load static %}

{% block content %}
<div class='container mt-4'>
    <div class="container-fluid">
        <div class="row">
        {% include 'includes/customer_sidebar.html' %}
        <div class="col-md-9 text-center">
            <!-- Page Content -->
            <h1>Welcome to your Dashboard</h1>
            <hr>
            <div class="container">
              <p>This is the main content of your dashboard.</p>
            </div>


        </div>
        </div>
        

        </div>
    </div>
</div>
{% endblock content %}

app/templates/customers/details_order.html
{% extends "includes/base.html" %}
{% load static %}

{% block content %}
<div class='container mt-4'>
  <div class="container-fluid">
      <div class="row">
      {% include 'includes/customer_sidebar.html' %}
          <div class="col-md-9 text-center card py-2">
        <h4 class="card-title text-center">Your Order</h4>
        <table class="table table-hover">
          <thead class="thead-dark">
            <tr>
              <th class="text-center" scope="col"> </th>
              <th class="text-center" scope="col">Shop</th>
              <th class="text-center" scope="col">Item</th>
              <th class="text-center" scope="col">Quantity</th>
              <th class="text-center" scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
            {% for item in orderitems %}
            <tr>
              {% with last_image=item.item.itemimage.latest %}
              <td class="text-center">
                <img class="img-fluid" style="max-height: 125px; width: auto;" src="{{ last_image.image.url }}" alt="{{ item.title }}">
              </td>
              {% endwith %}

              <td class="text-center"><a href="{% url 'marketplace:shop' item.item.shop.slug %}">{{ item.item.shop }}</a></td>
              <td class="text-center"><a href="{% url 'marketplace:item_details' item.item.slug %}">{{ item.item.name }}</a></td>
              <td class="text-center">{{ item.quantity }}</td>
              <td class="text-center">${{ item.item.price }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <div class='text-end'>
            Total:  ${{total}}
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

app/templates/customers/orders.html
{% extends "includes/base.html" %}
{% load static %}

{% block content %}
<div class='container mt-4'>
  <div class="container-fluid">
      <div class="row">
      {% include 'includes/customer_sidebar.html' %}
          <div class="col-md-9 text-center card py-2">
        <h4 class="card-title text-center">Your Orders</h4>
        {% if orders %}
        <table class="table table-hover">
          <thead class="thead-dark">
            <tr>
              <th class="text-center" scope="col"></th>
              <th class="text-center" scope="col">Date</th>
              <th class="text-center" scope="col">Sum</th>
            </tr>
          </thead>
          <tbody>
            {% for order in orders %}
            <tr>

              <td class="text-center">{{ forloop.counter }}</td>
              <td class="text-center"><a href="{% url 'customers:details_order' order.pk%}">{{ order.created_at|date:"F j, Y, g:i a" }}</a></td>
              <td class="text-center">${{ order.total_paid }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% if is_paginated %}
        <div class="pagination justify-content-center mt-4">
          <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
            <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a></li>
            {% endif %}
          </ul>
        </div>
        {% endif %}
        {% else %}
        <h4 class="card-title text-center">You do not have any orders yet.</h4>
        <div class="col text-center mt-3">
          <a class="btn btn-info btn-lg" href="{% url 'marketplace:home_view' %}">Go back</a>
      </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/customers/wish_list.html
{% extends "includes/base.html" %}
{% load static %}

{% block content %}
<div class='container mt-4'>
    <div class="container-fluid">
        <div class="row">
        {% include 'includes/customer_sidebar.html' %}
            <div class="col-md-9 text-center">
                <!-- Page Content -->
                <h1>Your Wish List</h1>
                <div style="display: none;" id='w-count'><h3>{{wish_count}}</h3></div>
                <hr>
                {% if wish_list %}

                <div id='empty-wishlist' class="row justify-content-center mt-3 mb-3" style="display: none;">
                    <h1>You do not have any products in your Wish List for now.</h1>
                    <div class="col text-center mt-3">
                        <a class="btn btn-info btn-lg" href="{% url 'marketplace:home_view' %}">Go back</a>
                    </div>
                </div>
                <div class="container">
                    <div class="row justify-content-center">

                            {% for item in items  %}
                                {% if item.is_approved and item.is_available and item in wish_list %}
                                <div id='wish-card-{{item.id}}' class="col-md-6">
                                    <div class="card mb-2" style="width: 18rem;">
                                        {% with last_image=item.itemimage.latest %}
                                            <img class='ml-2 mt-4 card-img-top ' id='blah' style='height: 125px; width: 254px; object-fit: cover;' src="{{ last_image.image.url }}" alt="{{ item.title }}">
                                        {% endwith %}
                                        <div class="card-body">
                                            <h5 class="card-title">{{item.name}}</h5>
                                            <p class="card-text">{{item.title}}</p>
                                            <p class="card-text">${{item.price}}</p>
                                            <div class="d-flex justify-content-center" style="gap: 10px;">
                                                <a href="{% url 'marketplace:item_details' item.slug %}" class="btn btn-primary">View</a>
                                                <form id='wish-page-{{item.id}}' action="{% url 'marketplace:add_wish' item.id %}"  method="POST">
                                                    {% csrf_token %}
                                                    <button id='page-btn-{{item.id}}' type="submit" class="btn btn-warning">


                                                            {% if item in request.user.wish_list.filter %}
                                                            <i id='fa-{{item.id}}' class="fa-solid fa-heart"></i>
                                                            {% else %}
                                                            <i id='fa-{{item.id}}' class="fa-regular fa-heart"></i>
                                                            {% endif %}



                                                    </button>
                                                </form>
                                                <form id='add-cart' method="POST" action="{% url 'cart:add-to-cart' item.pk %}">
                                                    {% csrf_token %}
                                                    <button id='add-cart-btn'  {% if in_cart %}disabled='true'{%endif%} type="submit" class="btn btn-warning btn-block">
                                                        {% if in_cart %}
                                                        <i id='fa-icon' class="fa fa-shopping-cart"></i>
                                                        {% else %}
                                                        <i id='fa-icon' class="fa fa-cart-plus"></i>
                                                        {% endif %}
                                                    </button>

                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                            {% endfor %}

                    </div>
                </div>
                {% if is_paginated %}
<div class="pagination justify-content-center mt-4">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a></li>
    {% endif %}
  </ul>
</div>
{% endif %}
                {% else %}
                    <div class="row justify-content-center mt-3 mb-3">
                        <h1>You do not have any products in your Wish List for now.</h1>
                        <div class="col-5 text-center mt-3">
                            <a class="btn btn-info btn-lg" href="{% url 'marketplace:home_view' %}">Go back</a>
                        </div>
                    </div>
                {% endif %}
            </div>

        </div>


        </div>
    </div>
</div>
<script>
    var wishCount = {{ wish_count }};
</script>
{% endblock content %}