app/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path(
        "add-to-cart/<int:pk>/",
        views.AddToCartView.as_view(),
        name="add-to-cart",
    ),
    path(
        "subtract-from-cart/<int:pk>/",
        views.SubtractFromCartView.as_view(),
        name="subtract-from-cart",
    ),
    path(
        "remove-from-cart/<int:pk>/",
        views.RemoveFromCartView.as_view(),
        name="remove-from-cart",
    ),
]

app/marketplace/urls.py
from django.urls import path

from . import views

app_name = "marketplace"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home_view"),
    path("add-wish/<int:id>/", views.AddToWishListView.as_view(), name="add_wish"),
    path("item-details/<slug:slug>", views.ItemFullView.as_view(), name="item_details"),
    path("shop/<slug:slug>/items/", views.ShopView.as_view(), name="shop"),
    path(
        "shop/<slug:slug>/items/<slug:category_slug>/",
        views.ShopView.as_view(),
        name="shop_by_category",
    ),
]

app/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"

urlpatterns = [
    path("add/", views.add, name="add"),
]

app/payment/urls.py
from django.urls import path

from . import views

app_name = "payment"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path("orderplaced/", views.order_placed, name="order_placed"),
    path("webhook/", views.stripe_webhook),
]

app/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path("", include("marketplace.urls")),
    path("shop-admin/", include("shop.urls")),
    path("customers/", include("customers.urls")),
    path("cart/", include("cart.urls")),
    path("payment/", include("payment.urls")),
    path("orders/", include("orders.urls")),
]
if settings.ADMIN_ENABLED:
    urlpatterns += [path("admin/", admin.site.urls)]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/orders/models.py
from django.contrib.auth import get_user_model
from django.db import models
from shop.models import Item, Shop


class Order(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="order_user",
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=14, blank=True)

    address = models.CharField(max_length=250, blank=True, null=True)
    country = models.CharField(max_length=16, blank=True, null=True)
    city = models.CharField(max_length=16, blank=True, null=True)
    state = models.CharField(max_length=40, blank=True, null=True)
    pin_code = models.CharField(max_length=15, blank=True, null=True)

    billing_status = models.BooleanField(default=False)
    order_key = models.CharField(max_length=200)
    total_paid = models.DecimalField(max_digits=7, decimal_places=2)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    def __str__(self):
        return str(self.created_at)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    item = models.ForeignKey(Item, related_name="order_items", on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.item.name) + "-" + str(self.item.shop) + "-" + str(self.order.order_key)[-8:-1]


class ShopOrder(models.Model):
    STATUS_CHOICES = (
        ("New", "New"),
        ("In Process", "In Process"),
        ("Sent", "Sent"),
    )

    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)

    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default="New")

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("shop", "order")
        ordering = ("-created_at",)

    def __str__(self):
        return f"{self.shop.shop_name} - {self.order}"

    def save(self, *args, **kwargs):
        order_items = self.order.items.filter(item__shop=self.shop)
        price = sum(item.quantity * item.price for item in order_items)
        self.price = price
        super().save(*args, **kwargs)

app/payment/views.py
import json

import stripe
from cart.models import Cart
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from orders.models import Order
from orders.views import payment_confirmation


class CartView(LoginRequiredMixin, TemplateView):
    template_name = "payment/home.html"

    def get(self, request, *args, **kwargs):
        cart_items = Cart.objects.filter(user=self.request.user).order_by("created_at")
        total = sum([it.quantity * it.item.price for it in cart_items])
        total = int(total * 100)

        stripe.api_key = settings.STRIPE_SECRET_KEY

        try:
            intent = stripe.PaymentIntent.create(amount=total, currency="gbp", metadata={"userid": 2})
        except stripe.error.StripeError as e:
            # Handle payment error
            error_message = str(e)
            return render(request, self.template_name, {"error_message": error_message})
        except stripe.error.CardError as e:
            # Display error message to the user
            err = e.error
            return render(request, self.template_name, {"error": err["message"]})

        return render(
            request,
            self.template_name,
            {
                "client_secret": intent.client_secret,
                "total": total / 100,
            },
        )


@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    event = None

    try:
        event = stripe.Event.construct_from(json.loads(payload), stripe.api_key)
    except ValueError as e:
        print(e)
        return HttpResponse(status=400)

    # Handle the event
    if event.type == "payment_intent.succeeded":
        payment_confirmation(event.data.object.client_secret)
    else:
        print("Unhandled event type{}".format(event.type))

    return HttpResponse(status=200)


def order_placed(request):
    user = request.user
    cart = Cart.objects.filter(user=user)
    order = Order.objects.filter(user=user).first()
    context = {
        "user": user,
        "order": order,
        "orderitems": order.items.all(),
        "total": order.total_paid,
    }
    cart.delete()
    return render(request, "payment/orderplaced.html", context=context)

app/templates/payment/home.html
{% extends "includes/base.html" %}
{% load static %}

{% block content %}



<div class="container text-center my-3">
<div class="container card">
    <div class="row">
        <div id="payment-form" class="col-12 col-lg-6 mx-auto">
          <h3 class="my-3">Billing address</h3>
          <!-- Error messages in this element -->
          <div id="card-errors" class="a" role="alert"></div>
          <form method="POST" action="{% url 'orders:add' %}">
            <div class="row">
              <div class="col-md-6 mb-2 pb-2">
                <label for="firstName" class="form-label">First Name</label>
                <input type="text" required class="form-control" id="firstName" value='{{request.user.first_name}}' placeholder="">
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
              <div class="col-md-6 mb-2 pb-2">
                <label for="lastName" class="form-label">Last Name</label>
                <input type="text"  class="form-control" id="lastName" value='{{request.user.last_name}}' placeholder="">
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6 mb-2 pb-2">
                <label for="phone_number" class="form-label">Phone number</label>
                <input type="text" required class="form-control" name='phone_number' id="id_phone_number" value='{% if request.user.userprofile.phone_number %}{{request.user.userprofile.phone_number}}{% endif %}' placeholder="">
              </div>
              <div class="col-md-6 mb-2 pb-2">
                <label for="email_address" class="form-label">Email address</label>
                <input type="email" required readonly class="form-control" name='email_address' id="id_email_address" value='{{request.user.email}}' onfocus="showEmailInfo()" onblur="hideEmailInfo()">
                <div id="email-info" class="text-muted" style="display: none;">In order to change email address please contact our customer service.</div>

              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <label class="form-label" for="address">Address</label>
                <input type="text" required name="address" value='{% if request.user.userprofile.address %}{{request.user.userprofile.address}}{% endif %}' maxlength="250" class="form-control form-control-lg pac-target-input" id="id_address" placeholder="Enter a location" autocomplete="off">
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 mb-2 pb-2">
                <label class="form-label" for="state">District</label>
                <input type="text" required name="state" value='{% if request.user.userprofile.state %}{{request.user.userprofile.state}}{% endif %}' maxlength="40" class="form-control form-control-lg" id="id_state">
              </div>
              <div class="col-md-6 mb-2 pb-2">
                <label class="form-label" for="city">City</label>
                <input type="text" required name="city" value='{% if request.user.userprofile.city %}{{request.user.userprofile.city}}{% endif %}' maxlength="16" class="form-control form-control-lg" id="id_city">
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 mb-2 pb-2">
                <label class="form-label" for="pin_code">Postal Code</label>
                <input type="text" required name="pin_code" value='{% if request.user.userprofile.pin_code %}{{request.user.userprofile.pin_code}}{% endif %}' maxlength="15" class="form-control form-control-lg" id="id_pin_code">
              </div>
              <div class="col-md-6 mb-2 pb-2">
                <label class="form-label" for="country  ">Country</label>
                <input type="text" required name="country" value='{% if request.user.userprofile.country %}{{request.user.userprofile.country }}{% endif %}' maxlength="16" class="form-control form-control-lg" id="id_country">
            </div>
          </div>
            <h4 class="mb-1">Payment</h4>
            <label for="card-element">Credit or debit card</label>
            <div id="card-element" class="form-control form-control-payment">
              <!-- Payment elements will appear here -->
            </div>

            <button id="submit" class="btn btn-primary w-100 fw-bold my-3" data-secret="{{ client_secret }}">Pay</button>
          </form>


        </div>
    </div>
</div>
<script>
    var CSRF_TOKEN = '{{ csrf_token }}'
    function showEmailInfo() {
      $('#email-info').show();
  }
  function hideEmailInfo() {
    $('#email-info').hide();
}
</script>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'js/payment.js' %}" data-rel-js></script>
{% endblock content %}

app/templates/payment/orderplaced.html
{% extends "includes/base.html" %}
{% load static %}

{% block content %}
<div class='container mt-4'>
  <div class="container-fluid">
      <div class="row">
      {% include 'includes/customer_sidebar.html' %}
          <div class="col-md-9 text-center card py-2">
        <h4 class="card-title text-center">Your Order</h4>
        <table class="table table-hover">
          <thead class="thead-dark">
            <tr>
              <th class="text-center" scope="col"> </th>
              <th class="text-center" scope="col">Item</th>
              <th class="text-center" scope="col">Shop</th>
              <th class="text-center" scope="col">Quantity</th>
              <th class="text-center" scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
            {% for item in orderitems %}
            <tr>
              {% with last_image=item.item.itemimage.latest %}
              <td class="text-center">
                <img class="img-fluid" style="max-height: 125px; width: auto;" src="{{ last_image.image.url }}" alt="{{ item.title }}">
              </td>
              {% endwith %}

              <td class="text-center"><a href="{% url 'marketplace:item_details' item.item.slug %}">{{ item.item.name }}</a></td>
              <td class="text-center"><a href="{% url 'marketplace:shop' item.item.shop.slug %}">{{ item.item.shop }}</a></td>
              <td class="text-center">{{ item.quantity }}</td>
              <td class="text-center">${{ item.item.price }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <div class='text-end'>
            <h4>Total:  ${{total}}</h4>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}