app/accounts/urls.py
from django.urls import path

from . import views
from .context_processors import daily_newsletter_form

app_name = "accounts"


urlpatterns = [
    path("login/", views.SignInView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("activate/<uidb64>/<token>/", views.ActivationView.as_view(), name="activate"),
    path("newsletter/", daily_newsletter_form, name="newsletter"),
    # reset password
    path("forgot_password/", views.ForgotPasswordView.as_view(), name="forgot_password"),
    path(
        "reset_password_validate/<uidb64>/<token>/",
        views.ValidatePasswordView.as_view(),
        name="validate_password",
    ),
    path("reset_password/", views.ResetPasswordView.as_view(), name="reset_password"),
]

app/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path(
        "add-to-cart/<int:pk>/",
        views.AddToCartView.as_view(),
        name="add-to-cart",
    ),
    path(
        "subtract-from-cart/<int:pk>/",
        views.SubtractFromCartView.as_view(),
        name="subtract-from-cart",
    ),
    path(
        "remove-from-cart/<int:pk>/",
        views.RemoveFromCartView.as_view(),
        name="remove-from-cart",
    ),
]

app/customers/urls.py
from django.urls import path

from . import views

app_name = "customers"


urlpatterns = [
    path("", views.CustomerPanelView.as_view(), name="customer_panel"),
    path(
        "profile-settings/",
        views.CustomerProfileView.as_view(),
        name="profile_settings",
    ),
    path("change-password/", views.ChangePasswordView.as_view(), name="change_password"),
    path("wish-list/", views.WishListView.as_view(), name="wish_list"),
    path("orders/", views.OrdersView.as_view(), name="orders"),
    path(
        "orders/details/<int:pk>/",
        views.OrderDetailView.as_view(),
        name="details_order",
    ),
]

app/marketplace/urls.py
from django.urls import path

from . import views

app_name = "marketplace"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home_view"),
    path("add-wish/<int:id>/", views.AddToWishListView.as_view(), name="add_wish"),
    path("item-details/<slug:slug>", views.ItemFullView.as_view(), name="item_details"),
    path("shop/<slug:slug>/items/", views.ShopView.as_view(), name="shop"),
    path(
        "shop/<slug:slug>/items/<slug:category_slug>/",
        views.ShopView.as_view(),
        name="shop_by_category",
    ),
]

app/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path("", include("marketplace.urls")),
    path("shop-admin/", include("shop.urls")),
    path("customers/", include("customers.urls")),
    path("cart/", include("cart.urls")),
    path("payment/", include("payment.urls")),
    path("orders/", include("orders.urls")),
]
if settings.ADMIN_ENABLED:
    urlpatterns += [path("admin/", admin.site.urls)]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/shop/urls.py
from django.urls import path

from . import views

app_name = "shop"

urlpatterns = [
    path("", views.ShopAdminView.as_view(), name="shop_admin"),
    # shop settings
    path("shop-settings/", views.ShopSettingsView.as_view(), name="shop_settings"),
    # CRUD category
    path("list-category/", views.CategoryListView.as_view(), name="list_category"),
    path("create-category/", views.CategoryCreateView.as_view(), name="create_category"),
    path(
        "update-category/<slug:slug>",
        views.CategoryUpdateView.as_view(),
        name="update_category",
    ),
    path(
        "delete-category/<slug:slug>",
        views.CategoryDeleteView.as_view(),
        name="delete_category",
    ),
    path(
        "detail-category/<slug:slug>",
        views.CategoryDetailView.as_view(),
        name="detail_category",
    ),
    # CRUD item
    path("list-item/", views.ItemListView.as_view(), name="list_item"),
    path("create-item/", views.ItemCreateView.as_view(), name="create_item"),
    path("update-item/<slug:slug>", views.ItemUpdateView.as_view(), name="update_item"),
    path("delete-item/<slug:slug>", views.ItemDeleteView.as_view(), name="delete_item"),
    path("detail-item/<slug:slug>", views.ItemDetailView.as_view(), name="detail_item"),
    path("orders/", views.OrdersView.as_view(), name="orders"),
    path(
        "orders/details/<int:pk>/",
        views.OrdersDetailView.as_view(),
        name="details_order",
    ),
    path("customers/", views.CustomersView.as_view(), name="customers"),
    path(
        "customers/orders/<int:customer_id>/",
        views.CustomerOrdersViews.as_view(),
        name="customers_orders",
    ),
    path(
        "orders/update-status/<int:pk>/",
        views.UpdateOrderStatusView.as_view(),
        name="update_order_status",
    ),
    path(
        "super-user-panel/shops/",
        views.SuperUserPanelShops.as_view(),
        name="super_user_panel_shops",
    ),
    path(
        "super-user-panel/items/",
        views.SuperUserPanelItems.as_view(),
        name="super_user_panel_shops_items",
    ),
    path(
        "super-user-panel/shop/<slug:slug>",
        views.ShopDetailAdminView.as_view(),
        name="super_user_detail_shop",
    ),
    path(
        "super-user-panel/item/<slug:slug>",
        views.ItemDetailAdminView.as_view(),
        name="super_user_detail_item",
    ),
    path(
        "shop_approved/<slug:slug>/",
        views.ShopApprovedView.as_view(),
        name="shop_approved",
    ),
    path(
        "item_approved/<slug:slug>/",
        views.ItemApprovedView.as_view(),
        name="item_approved",
    ),
]

app/templates/includes/alerts.html
{% if messages %}
    {% for message in messages %}
        <div id='myAlert' class="alert alert-{{message.tags}} alert-dismissible fade show shadow-risen rounded-pill show-notification">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <strong>{{message}}</strong>
          </div>
    {% endfor %}

{% endif %}

app/templates/includes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>shopOnline</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">



    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!-- Bootstrap-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://kit.fontawesome.com/ce33396891.js" crossorigin="anonymous"></script>


    <!-- Custom CSS-->
    <link href="{% static 'css/custom.css' %}" type="text/css" rel="stylesheet">
    <!-- Custom JS-->
    <script src="{% static 'js/custom.js' %}"></script>
    <!-- JS for Google Location-->
    <script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete&language=en" defer></script>
</head>
<body>
<section class="vh-100 wrapper"style="background-color: #a1a7c6;">
{% include 'includes/navbar.html' %}

<div class="row justify-content-center">
    <div class="col-4">
        {% include 'includes/alerts.html' %}
    </div>
</div>
<main class="main">
    {% block content %}

    {% endblock content %}
</main>

{% include 'includes/footer.html' %}
</section>
<script>
    var myAlert = document.getElementById('myAlert')
    var bsAlert = new bootstrap.Alert(myAlert)


</script>
</body>
</html>

app/templates/includes/cover.html
{% comment %} {% load static %}
<div class="main-section">
    <div class="page-section restaurant-detail-image-section" style=" background:url({% if request.user.shop.cover_photo %}{{ request.user.shop.cover_photo.url }}{% endif %}) no-repeat scroll 0 0 / cover;">
    <!-- Container Start -->
        <div class="container">
            <!-- Row Start -->
            <div class="row">
                <!-- Column Start -->
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="company-info-detail">
                        <div class="company-info">
                            <div class="img-holder">
                                <figure>
                                    <img src="{% if vendor.user_profile.profile_picture %}{{ vendor.user_profile.profile_picture.url }}{% else %}{% static 'logo/anonymous.png' %}{% endif %}" alt="">
                                </figure>
                            </div>

                            <div class="text-holder">
                                <span class="restaurant-title">{{ vendor.vendor_name}}</span>
                                <div class="text">
                                    <i class="icon-location"></i>
                                    <p>{{vendor.user_profile.address}},
                                        {{vendor.user_profile.country}},
                                        {{vendor.user_profile.pin_code}},
                                        {{vendor.user_profile.city}},
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Column End -->
            </div>
            <!-- Row End -->
        </div>
        <!-- Container End -->
    </div>
</div> {% endcomment %}

app/templates/includes/customer_sidebar.html
<div class="col-md-3 ">
    <!-- Sidebar -->
    <div class="list-group ">
    <a href="{% url 'customers:customer_panel' %}" class="list-group-item list-group-item-action {% if '/customers/' == request.path %}active{% endif %}">Dashboard</a>
    <a href="{% url 'customers:wish_list' %}" class="list-group-item list-group-item-action {% if 'wish-list' in request.path %}active{%endif%}">Wishlist</a>
    <a href="{% url 'customers:profile_settings'  %}" class="list-group-item list-group-item-action {% if 'profile-settings' in request.path %}active{%endif%}">Profile</a>
    <a href="{% url 'customers:change_password' %}" class="list-group-item list-group-item-action {% if 'change-password' in request.path %}active{%endif%}">Change password</a>
    <a href="{% url 'customers:orders' %}" class="list-group-item list-group-item-action {% if 'orderplaced' in request.path or 'orders' in request.path %}active{%endif%}">Orders</a>
    <a href="{% url 'accounts:logout' %}" class="list-group-item list-group-item-action">Logout</a>
    </div>
</div>

app/templates/includes/footer.html
<footer class="bg-dark text-center footer">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Form -->
    <section class="">
      <form id='newsletter-form'  autocomplete="off" >
        {% csrf_token %}
        <!--Grid row-->
        <div class="row d-flex justify-content-center">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong class='text-light'>Sign up for our newsletter</strong>
            </p>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div class="form-outline mb-4">
              {% comment %} <input type="email" name="daily-email" maxlength="100" required id="daily-email-id" class="form-control"> {% endcomment %}
              {{d_form.email}}

              <label class="form-label text-light" for="daily-email">Email address</label>
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-auto">
            <!-- Submit button -->
            <button type='submit' class='btn btn-primary mb-4 text-light' id="report-btn">
              Subscribe
            </button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </form>
    </section>
    <!-- Section: Form -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/templates/includes/navbar.html
{% load static %}
<nav class='container bg-primary text-white rounded-pill'>
    <div class="row mb-2 py-2 px-2">
        <div class="col-2 text-start mt8" >
            <a
             class="navbar-brand" href="{% url 'marketplace:home_view' %}"><i class="fa-solid fa-store fa-2xl d-inline-block"></i><h2 class='d-inline-block'>shopOnline</h2></a>
        </div>
        {% if request.user.is_superuser %}
          <div class="col-5 text-end fw-bolder msr">
            <h3><a class="text-white" href="{% url 'shop:super_user_panel_shops' %}">{% if new_items %}<span class="badge bg-warning bgg" id='cart_counter'>
              {{new_items}}</span>{%endif%}Marketplace{% if new_shops %}<span class="badge bg-danger bgg" id='cart_counter'>
              {{new_shops}}</span>{%endif%}</a></h3>
          </div>
        {% else %}
          <div class="col-5 text-end fw-bolder mt13" >
            <h3>Marketplace</h3>
          </div>
        {% endif %}

        <div class="col-5 text-end pe-2 fw-bolder mt8">
            {% if not request.user.is_authenticated %}
            <div class='text-light'>Hello, Visitor!</div>
            <a class='text-light text-decoration-none' href="{% url 'cart:cart' %}">

              <i class="fa fa-shopping-cart fs20"></i>
                  <span id='cart-c' class="badge badge-warning nng" id='cart_counter'>
                    {{cart_count}}
                  </span>
            </a>
            <a  class='text-light' href="{% url 'accounts:login' %}">Login</a>
            <span>|</span>
            <a  class='text-light' href="{% url 'accounts:signup' %}">SignUp</a>

            {% else %}
            <a class='text-light text-decoration-none' href="{% url 'cart:cart' %}">
              <i class="fa fa-shopping-cart fs20"></i>
                  <span id='cart-c' class="badge badge-warning" id='cart_counter nng'>
                    {{cart_count}}</span>
            </a>

            {% if request.user.is_staff  and request.user.shop.is_approved %}

            <div class='d-inline-block mx-3  dropdown'>

                <button class="btn btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-bs-toggle='dropdown' aria-expanded="false">
                    <img id='navav' src="{% if request.user.shop.avatar %}{{ request.user.shop.avatar.url }}{% else %}{% static 'anonymous.png' %}{% endif %}" class='navav'>
                    {{ request.user.shop.shop_name }}<span class="badge bg-danger tp10">{% if new_orders_count %}{{new_orders_count}}{% endif %}</span>
                  </button>
                  <ul class="dropdown-menu dropdown-menu-dark text-center" aria-labelledby="dropdownMenuButton">
                    <li><a href="{% url 'shop:shop_admin' %}" class="dropdown-item">Dashboard</a></li>
                    <a href="{% url 'marketplace:shop' request.user.shop.slug %}" class="dropdown-item">Preview</a>
                    <a href="{% url 'shop:shop_settings' %}" class="dropdown-item">Shop's settings</a>
                    <li><a href="{% url 'shop:list_category' %}" class="dropdown-item">Categories</a></li>
                    <li><a href="{% url 'shop:list_item' %}" class="dropdown-item">Products</a></li>
                    <li><a href="{% url 'shop:orders' %}" class="dropdown-item">Orders<span class="badge bg-danger">{% if new_orders_count %}{{new_orders_count}}{% endif %}</span></a></li>
                    <li><a href="{% url 'shop:customers' %}" class="dropdown-item">Customers</a></li>
                    <li><a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a></li>
                  </ul>
            </div>
            {% endif %}
            <div class='d-inline-block mx-3  dropdown'>

                <button class="btn btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-bs-toggle='dropdown' aria-expanded="false">
                    <img id='navav' src="{% if request.user.userprofile.profile_picture %}{{ request.user.userprofile.profile_picture.url }}{% else %}{% static 'anonymous.png' %}{% endif %}" class='navav'>
                    {{ request.user.first_name }}
                  </button>
                  <ul class="dropdown-menu dropdown-menu-dark text-center" aria-labelledby="dropdownMenuButton">
                    <li><a href="{% url 'customers:customer_panel' %}" class="dropdown-item">Dashboard</a></li>
                    <li><a href="{% url 'customers:wish_list' %}" class="dropdown-item">Wishlist</a></li>
                    <li><a href="{% url 'customers:profile_settings' %}" class="dropdown-item">Profile</a></li>
                    <li><a href="{% url 'customers:change_password' %}" class="dropdown-item">Change password</a></li>
                    <li><a href="{% url 'customers:orders' %}" class="dropdown-item">Orders</a></li>
                    <li><a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a></li>
                  </ul>
            </div>


            {% endif %}

        </div>

    </div>

  </nav>

app/templates/includes/shop_sidebar.html
<div class="col-md-3">
    <!-- Sidebar -->
    <div class="list-group">
    <a href="{% url 'shop:shop_admin' %}" class="list-group-item list-group-item-action {% if '/shop-admin/' == request.path %}active{% endif %}">Dashboard</a>
    <a href="{% url 'marketplace:shop' request.user.shop.slug %}" class="list-group-item list-group-item-action">Preview</a>
    <a href="{% url 'shop:shop_settings' %}" class="list-group-item list-group-item-action {% if 'shop-settings' in request.path %}active{% endif %}">Shop's settings</a>
    <a href="{% url 'shop:list_category' %}" class="list-group-item list-group-item-action {% if 'list-category' in request.path or 'detail-category' in request.path or 'update-category' in request.path%}active{%endif%}">Categories</a>
    <a href="{% url 'shop:list_item' %}" class="list-group-item list-group-item-action {% if 'list-item' in request.path or 'update-item' in request.path or 'detail-item' in request.path%}active{%endif%}">Products</a>
    <a href="{% url 'shop:orders' %}" class="list-group-item list-group-item-action {% if 'orders' in request.path or  'customers/orders' in request.path %}active{%endif%}">Orders <span class="badge bg-danger">{% if new_orders_count %}{{new_orders_count}}{% endif %}</span></a>
    <a href="{% url 'shop:customers' %}" class="list-group-item list-group-item-action {% if 'customers' in request.path and  'orders' not in request.path%}active{%endif%}">Customers</a>
    </div>
</div>