app/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path(
        "add-to-cart/<int:pk>/",
        views.AddToCartView.as_view(),
        name="add-to-cart",
    ),
    path(
        "subtract-from-cart/<int:pk>/",
        views.SubtractFromCartView.as_view(),
        name="subtract-from-cart",
    ),
    path(
        "remove-from-cart/<int:pk>/",
        views.RemoveFromCartView.as_view(),
        name="remove-from-cart",
    ),
]

app/marketplace/urls.py
from django.urls import path

from . import views

app_name = "marketplace"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home_view"),
    path("add-wish/<int:id>/", views.AddToWishListView.as_view(), name="add_wish"),
    path("item-details/<slug:slug>", views.ItemFullView.as_view(), name="item_details"),
    path("shop/<slug:slug>/items/", views.ShopView.as_view(), name="shop"),
    path(
        "shop/<slug:slug>/items/<slug:category_slug>/",
        views.ShopView.as_view(),
        name="shop_by_category",
    ),
]

app/payment/urls.py
from django.urls import path

from . import views

app_name = "payment"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path("orderplaced/", views.order_placed, name="order_placed"),
    path("webhook/", views.stripe_webhook),
]

app/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path("", include("marketplace.urls")),
    path("shop-admin/", include("shop.urls")),
    path("customers/", include("customers.urls")),
    path("cart/", include("cart.urls")),
    path("payment/", include("payment.urls")),
    path("orders/", include("orders.urls")),
]
if settings.ADMIN_ENABLED:
    urlpatterns += [path("admin/", admin.site.urls)]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/cart/models.py
from django.contrib.auth import get_user_model
from django.db import models
from shop.models import Item


class Cart(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="cart_items",
    )
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="cart_items")
    quantity = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.item.name

app/cart/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views import generic
from django.views.generic.base import View
from shop.models import Item

from .cart import CookiesCart
from .models import Cart


class AddToCartView(View):
    """
    Add an item to the cart
    """

    def post(self, request, *args, **kwargs):
        item = get_object_or_404(Item, pk=self.kwargs["pk"])
        if request.user.is_authenticated:
            cart_item, created = Cart.objects.get_or_create(user=request.user, item=item)
            if not created:
                cart_item.quantity += 1
                cart_item.save()
            return JsonResponse(
                {
                    "message": "Added to the Cart!",
                    "icon": "success",
                }
            )
        else:
            cart = CookiesCart(request)
            cart.add(item)
            return JsonResponse(
                {
                    "message": "Added to the Cart!",
                    "icon": "success",
                }
            )


class SubtractFromCartView(View):
    def post(self, request, *args, **kwargs):
        item = get_object_or_404(Item, id=self.kwargs["pk"])

        if request.user.is_authenticated:
            cart_item = get_object_or_404(Cart, user=request.user, item=item)
            if cart_item.quantity > 1:
                cart_item.quantity -= 1
                cart_item.save()
            else:
                cart_item.delete()
        else:
            cart = CookiesCart(request)
            cart.subtract(item)

        return JsonResponse(
            {
                "message": "Removed from the Cart!",
                "icon": "warning",
            }
        )


class RemoveFromCartView(View):
    def post(self, request, *args, **kwargs):
        item = get_object_or_404(Item, id=self.kwargs["pk"])

        if request.user.is_authenticated:
            cart_item = get_object_or_404(Cart, user=request.user, item=item)
            cart_item.delete()
        else:
            cart = CookiesCart(request)
            cart.delete(item)

        return JsonResponse(
            {
                "message": "Deleted from the Cart!",
                "icon": "warning",
            }
        )


class CartView(generic.TemplateView):
    template_name = "marketplace/cart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            # Get cart items for logged in user
            cart_items = Cart.objects.filter(user=self.request.user).order_by("created_at")
            cart_count = sum([it.quantity for it in cart_items])
            context["cart_counter"] = cart_count
            context["total"] = sum([it.quantity * it.item.price for it in cart_items])
        else:
            # Get cart items from session for anonymous user
            cart = CookiesCart(self.request)
            cart_items = cart.get_items()
            cart_count = len(cart_items)

            context["total"] = cart.get_total_price()

        context["cart_items"] = cart_items
        context["cart_counter"] = cart_count

        return context

app/marketplace/views.py
from cart.cart import CookiesCart
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views import View, generic
from shop.models import Category, Item, Shop


class HomeView(generic.ListView):
    model = Item
    template_name = "marketplace/home.html"
    context_object_name = "items"
    paginate_by = 8

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ShopView(generic.ListView):
    template_name = "marketplace/shop_page.html"
    context_object_name = "items"
    paginate_by = 8

    def get_queryset(self):
        shop = Shop.objects.get(slug=self.kwargs["slug"])
        category_slug = self.kwargs.get("category_slug")
        items = Item.objects.filter(shop=shop, is_approved=True)
        if category_slug:
            category = Category.objects.filter(shop=shop, slug=category_slug).first()
            if category:
                items = items.filter(category=category, is_approved=True)

        return items

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["shop"] = Shop.objects.get(slug=self.kwargs["slug"])
        cat = Category.objects.filter(shop=context["shop"])
        categories = []
        for i in cat:
            if i.items.filter(is_approved=True).exists():
                categories.append(i)
        context["categories"] = categories
        category_slug = self.kwargs.get("category_slug")
        if category_slug:
            shop = Shop.objects.get(slug=self.kwargs["slug"])
            context["current_category"] = "Category: {}".format(
                Category.objects.filter(shop=shop, slug=category_slug).first()
            )
        else:
            context["current_category"] = "All Products"
        context["selected_category"] = self.kwargs.get("category_slug")
        return context


class AddToWishListView(LoginRequiredMixin, View):
    login_required_message = "Please log in to add product to Wish List"

    def post(self, request, id):
        item = get_object_or_404(Item, id=id)
        if item.wish_list.filter(id=self.request.user.id).exists():
            item.wish_list.remove(self.request.user)
            return JsonResponse(
                {
                    "message": '"{}" has been removed from WishList.'.format(item.name),
                    "icon": "warning",
                    "item_id": item.id,
                }
            )
        else:
            item.wish_list.add(self.request.user)
            return JsonResponse(
                {
                    "message": '"{}" has been added to WishList.'.format(item.name),
                    "icon": "success",
                    "item_id": item.id,
                }
            )

    def dispatch(self, request, *args, **kwargs):
        # redirect if request method Get
        if self.request.method == "GET":
            return redirect("marketplace:home_view")
        # show reason of login
        elif not self.request.user.is_authenticated:
            # messages.warning(self.request, self.login_required_message)
            return JsonResponse(
                {
                    "message": self.login_required_message,
                    "icon": "error",
                }
            )
        return super().dispatch(request, *args, **kwargs)


class ItemFullView(generic.DetailView):
    queryset = Item.objects.all()
    template_name = "marketplace/item_details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_item"] = self.get_object()
        if self.request.user.is_authenticated:
            context["in_cart"] = self.request.user.cart_items.filter(item=self.get_object()).exists()
        else:
            cart = CookiesCart(self.request)
            cart_items = []
            for item_id, item_data in cart.cart.items():
                item = Item.objects.get(pk=item_id)
                qty = item_data.get("qty")
                cart_items.append(
                    {
                        "item": item,
                        "quantity": qty,
                    }
                )
            cart_items = sorted(cart_items, key=lambda x: x["item"].created_at)
            cart_item_ids = [item["item"].id for item in cart_items]
            in_cart = self.get_object().id in cart_item_ids

            context["in_cart"] = in_cart
            context["cart_itemss"] = cart_items
        return context

app/templates/marketplace/cart.html
{% extends "includes/base.html" %}
{% load mermaid %}

{% load static %}
{% block content %}
<div class='container mt-4'>
    <div class="container-fluid">
        <div class="row">
        {% include 'includes/customer_sidebar.html' %}
            <div class="col-md-9 text-center card">
              <div class="text-center p-5" id="empty-cart" style="display: none;">
                <h3>Cart is dempty</h3>

              </div>

                <div id='tab' class="container my-5">
                    <h1 class="mb-4">Your Cлart</h1>
                    {% mermaid "graph LR; A-->B;" %}


                    {% if cart_items %}
                      <table class="table table-hover">
                        <thead>
                          <tr>
                            <th scope="col">Item</th>
                            <th scope="col">Shop</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Price</th>
                            <th scope="col">Delete</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for cart_item in cart_items %}
                            <tr id='tr-{{cart_item.item.id}}'>
                              <td><a href="{% url 'marketplace:item_details' cart_item.item.slug %}">{{ cart_item.item.name }}</a></td>
                              <td><a href="{% url 'marketplace:shop' cart_item.item.shop.slug %}">{{ cart_item.item.shop }}</a></td>
                              <td  class="d-flex gap-4 justify-content-center">

                                  <form id='subtract-cart-{{cart_item.item.pk}}' method="POST" action="{% url 'cart:subtract-from-cart' cart_item.item.pk %}">
                                    {% csrf_token %}
                                    <button id='subtract-cart-btn-{{cart_item.item.pk}}' type="submit" class="btn btn-danger btn-block"><i class="fas fa-minus"></i></button>
                                  </form>

                                  <div id='qty-{{cart_item.item.id}}'>
                                    {{ cart_item.quantity }}
                                  </div>

                                  <form id='add-cart-{{cart_item.item.pk}}' method="POST" action="{% url 'cart:add-to-cart' cart_item.item.pk %}">
                                    {% csrf_token %}
                                    <button id='add-cart-btn-{{cart_item.item.pk}}' type="submit" class="btn btn-primary btn-block"><i class="fa fa-plus"></i></button>
                                  </form>



                              </td>
                              <td>
                                <div id='price-{{cart_item.item.id}}'>
                                  {{ cart_item.item.price }}
                                </div>
                              </td>
                              <td>
                                <form id='remove-cart-{{cart_item.item.pk}}' method="POST" action="{% url 'cart:remove-from-cart' cart_item.item.pk %}">
                                  {% csrf_token %}
                                  <button id='remove-cart-btn-{{cart_item.item.pk}}' type="submit" class="btn btn-dark btn-block"><i class="fa fa-trash-alt"></i></button>
                                </form>
                              </td>
                            </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                      <hr>
                      <h4>Total:$<span id='ttott'>{{total}}</span></h2>
                        <a type='button' href="{% url 'payment:cart' %}" class='btn btn-success'>Buy now!</a>
                    {% else %}
                    <h3>Cart is empty</h3>
                    {% endif %}
                  </div>
            </div>
        </div>

    </div>

{% endblock content %}

app/templates/marketplace/home.html
{% extends "includes/base.html" %}
{% load static %}


{% block content %}



<div class="container text-center">

<div class="container my-5">
    <div class="row">
        {% for item in items  %}
            {% if item.is_approved and item.is_available %}
            <div class="col-md-3">
                <div class="card mb-2" style="width: 18rem;">
                    {% with last_image=item.itemimage.latest %}
                        <img class='ml-2 mt-4 card-img-top ' id='blah' style='height: 125px; width: 254px; object-fit: cover;' src="{{ last_image.image.url }}" alt="{{ item.title }}">
                    {% endwith %}

                    <div class="card-body">

                        <h5 class="card-title">{{item.name}}</h5>
                        <p class="card-text">{{item.title}}</p>
                        <p class="card-text">${{item.price}}</p>
                        <div class="d-flex justify-content-center" style="gap: 10px;">
                            <a href="{% url 'marketplace:item_details' item.slug %}" class="btn btn-primary">View</a>
                            <form id='wish-form-{{item.id}}' action="{% url 'marketplace:add_wish' item.id %}"  method="POST">
                                {% csrf_token %}
                                <button id='wish-btn-{{item.id}}' type="submit" class="btn btn-warning">


                                        {% if item in request.user.wish_list.filter %}
                                        <i id='fa-{{item.id}}' class="fa-solid fa-heart"></i>
                                        {% else %}
                                        <i id='fa-{{item.id}}' class="fa-regular fa-heart"></i>
                                        {% endif %}



                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

{% if is_paginated %}
<div class="pagination justify-content-center mt-4">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a></li>
    {% endif %}
  </ul>
</div>
{% endif %}

{% endblock content %}

app/templates/marketplace/item_details.html
{% extends "includes/base.html" %}
{% load static %}

{% block content %}

<div class='container my-4'>
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-12 text-center">
                <div class="card mt-2">
                    <div class="row text-justify">
                        <div class="col-5">
                            {% with last_image=object.itemimage.latest %}
                                <img class='ml-2 mt-4 img-thumbnail'id='blah' height='125' src="{{ last_image.image.url }}" alt="{{ item.title }}">
                            {% endwith %}
                        </div>
                        <div class="col-7">
                            <div class="row mb-2 mt-4 text-center">
                                <div class="col-7">
                                    <h2 style='margin-bottom: -6px;'>{{object.name}}</h2>
                                    <small>{{object.title}}</small>
                                </div>
                            </div>

                            <div class="row my-2">
                                <div class="col-5">
                                    Category:
                                    <hr>
                                </div>
                                <div class="col-7">
                                    {{object.category.name}}
                                    <hr>
                                </div>
                            </div>
                            <div class="row my-2">
                                <div class="col-5">
                                    Shop:
                                    <hr>
                                </div>
                                <div class="col-7">
                                    <a href="{% url 'marketplace:shop' object.shop.slug %}">{{object.shop.shop_name}}</a>

                                    <hr>
                                </div>
                            </div>
                            <div class="row my-2">
                                <div class="col-5">
                                    Price:
                                    <hr>
                                </div>
                                <div class="col-7">
                                    ${{object.price}}
                                    <hr>
                                </div>
                            </div>
                            <div>
                            </div>
                            <div class="row my-2">
                                <div class="col d-flex justify-content-center align-items-center p-2 gap-4">
                                    <button class='btn btn-danger btn-block'>Buy now</button>
                                    <form id='wish-form-{{item.id}}' action="{% url 'marketplace:add_wish' item.id %}" method="POST">
                                        {% csrf_token %}
                                        <button id='wish-btn-{{item.id}}' type="submit" class="btn btn-info btn-block">

                                            {% if item in request.user.wish_list.filter %}
                                            <i id='fa-{{item.id}}' class="fa-solid fa-heart"></i>
                                            {% else %}
                                            <i id='fa-{{item.id}}' class="fa-regular fa-heart"></i>
                                            {% endif %}

                                        </button>
                                    </form>

                                    <form id='add-cart' method="POST" action="{% url 'cart:add-to-cart' object.pk %}">
                                        {% csrf_token %}
                                        <button id='add-cart-btn'  {% if in_cart %}disabled='true'{%endif%} type="submit" class="btn btn-warning btn-block">
                                            {% if in_cart %}
                                            <i id='fa-icon' class="fa fa-shopping-cart"></i>
                                            {% else %}
                                            <i id='fa-icon' class="fa fa-cart-plus"></i>
                                            {% endif %}
                                        </button>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="row my-2">
                            <div class="col-5">
                                Description:
                                <hr>
                            </div>
                            <div class="col-12">
                                {{object.description}}

                            </div>
                        </div>
                    </div>
                </div>
            </div>

    </div>
</div>


{% endblock content %}

app/templates/marketplace/shop_page.html
{% extends "includes/base.html" %}
{% load static %}

{% block content %}

<div class='container my-2'>

        <div class="page-section restaurant-detail-image-section text-light rounded-pill" style=" max-height: 146px; background:url({% if shop.cover_photo %}{{ shop.cover_photo.url }}{% endif %}) no-repeat scroll 0 0 / cover;">
        <div class="row" style="
        height: 148px;">
            <div class="col-6 mt-3">
                <h1 style='margin-left: 77px;'><i class="fa-solid fa-shop"></i>{{shop.shop_name}}</h1>
            </div>
            <div class="col-6 text-center mt-3">
                <img class='img-thumbnail' style='margin-left: 8rem !important; margin-top: 0.5rem;; height: 100px' src="{% if shop.avatar %}{{shop.avatar.url}}{% endif %}" alt="asdfasdf ">

            </div>
        </div>

        </div>
</div>
{% if items %}
<div class="container my-2">
    <div class="text-center rounded-pill">
        <div class="row no-gap " style="height: 43px;">
            <div class="col-3" style="margin-right: -13px;">
                <p class="btn btn-dark form-control">
                    {{current_category}}
                </p>
            </div>
            {% comment %} <div class="col-3" style="margin-right: -13px;">
                <p class="btn btn-dark form-control">
                    Filter by:
                </p>
            </div> {% endcomment %}
            <div class="col-3">
                <div class="d-inline-block mx-3 drowdown ml-" style="width:100%;position: relative;">

                    <button class="btn btn-dark form-control drowdown-toggle" type='button' id='dropdownMenuButton' data-bs-toggle='dropdown' aria-expanded='false'>
                        <i class="fa-regular fa-square-caret-down"></i> Categories <span class="badge bg-secondary">Filter by</span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-dark text-center" aria-labelledby='dropdownMenuButton'  style="position: absolute; width: 100%;">
                        <li><a class='dropdown-item' href="{% url 'marketplace:shop' shop.slug %}">All</a></li>
                        {% for category in categories %}
                        <li><a class="dropdown-item" href="{% url 'marketplace:shop_by_category' shop.slug category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>

                </div>

            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        {% for item in items  %}
            {% if item.is_approved and item.is_available %}
            <div class="col-md-3">
                <div class="card mb-2" style="width: 18rem;">
                    {% with last_image=item.itemimage.latest %}
                        <img class='ml-2 mt-4 card-img-top ' id='blah' style='height: 125px; width: 254px; object-fit: cover;' src="{{ last_image.image.url }}" alt="{{ item.title }}">
                    {% endwith %}
                    <div class="card-body">
                        <h5 class="card-title">{{item.name}}</h5>
                        <p class="card-text">{{item.title}}</p>
                        <p class="card-text">${{item.price}}</p>
                        <div class="d-flex justify-content-center" style="gap: 10px;">
                            <a href="{% url 'marketplace:item_details' item.slug %}" class="btn btn-primary">View</a>
                            <form id='wish-form-{{item.id}}' action="{% url 'marketplace:add_wish' item.id %}"  method="POST">
                                {% csrf_token %}
                                <button id='wish-btn-{{item.id}}' type="submit" class="btn btn-warning">


                                        {% if item in request.user.wish_list.filter %}
                                        <i id='fa-{{item.id}}' class="fa-solid fa-heart"></i>
                                        {% else %}
                                        <i id='fa-{{item.id}}' class="fa-regular fa-heart"></i>
                                        {% endif %}



                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
        {% if is_paginated %}
            <div class="pagination justify-content-center mt-4">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                    {% endif %}

                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}

    </div>
</div>
{% else %}
<div class="container">
    <div class="row mt-5">
        <h3 class='text-center'>We are currently working on our products.</h3>
        <h6 class='text-center'>We are sorry for inconvenience.</h6>
    </div>
</div>
{% endif %}

{% endblock content %}